# Generated by Django 4.0.4 on 2022-05-19 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='movies.director'),
        ),
    ]
