# Generated by Django 4.0.4 on 2022-05-20 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_director'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title', 'descriptions', 'created_at', 'updated_at', 'director'], 'verbose_name': 'Кино', 'verbose_name_plural': 'Кино'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.director'),
        ),
    ]
